version: '3.8'

services:
  ppe_monitor:
    image: ppe-monitor
    container_name: ppe_container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - /dev/video0:/dev/video0
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "8501:8501"
    runtime: nvidia